version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    networks:
      - app_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    networks:
      - app_network

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    networks:
      - app_network

networks:
  app_network: